
modLoader="kotlinforforge" #mandatory
loaderVersion="[4.11,)" #mandatory (24 is current forge version)
issueTrackerURL="https://github.com/MayaqqDev/Cynosure/issues" #optional
displayURL="https://github.com/MayaqqDev/Cynosure/issues" #optional
authors="$mod_author" #optional
logoFile="assets/cynosure/icon.png"
license = "$license"

[[mods]] #mandatory
modId="$mod_id" #mandatory
version="$version" #mandatory
displayName="$mod_name" #mandatory
description="$description"

[[dependencies.$mod_id]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[47,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.$mod_id]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.$mod_id]]
modId="kotlinforforge"
mandatory=true
versionRange="[4.11,)"
ordering="NONE"
side="BOTH"